namespace MyApp.Api.DTOs
{
    /// <summary>What the importer decided about one item, before anything is written.</summary>
    public static class OpeningStockRowStatus
    {
        /// <summary>An item type with this exact name and HS code already exists — its
        /// opening quantity is updated and no catalog row is created.</summary>
        public const string Matched = "matched";

        /// <summary>The HS code already has an auto-generated placeholder item type;
        /// it is reused and renamed to the sheet's name.</summary>
        public const string MatchedRenamed = "matched-renamed";

        /// <summary>The name matches an item type that carries no HS code; it is reused
        /// and the code filled in.</summary>
        public const string MatchedClassified = "matched-classified";

        /// <summary>The name matches an existing item type carrying a DIFFERENT HS code.
        /// The operator picks: reuse that one, or create a separate item.</summary>
        public const string Ambiguous = "ambiguous";

        /// <summary>Nothing matched — a new item type is created.</summary>
        public const string WillCreate = "will-create";

        /// <summary>The HS code is not in the tariff master. Blocking.</summary>
        public const string HsUnknown = "hs-unknown";

        /// <summary>Unusable as it stands — no name, no quantity. Blocking.</summary>
        public const string Error = "error";
    }

    /// <summary>An existing item type offered as a choice on an ambiguous row.</summary>
    public class OpeningStockCandidateDto
    {
        public int ItemTypeId { get; set; }
        public string Name { get; set; } = "";
        public string? HsCode { get; set; }
        public bool IsAutoGenerated { get; set; }
    }

    /// <summary>
    /// One item as the importer read it — already grouped, so an item spread
    /// across several customs lots appears once with its quantities summed.
    /// </summary>
    public class OpeningStockRowDto
    {
        /// <summary>Row numbers in the source sheet that fed this item, so a
        /// query can be traced back to the workbook.</summary>
        public List<int> SourceRows { get; set; } = new();

        public string ItemName { get; set; } = "";
        public string? HsCode { get; set; }

        /// <summary>True when only a 4-digit heading was available. FBR rejects
        /// those for sales, so the item type is flagged and the operator has to
        /// pick a full code before it can be billed.</summary>
        public bool IsHsCodePartial { get; set; }

        public string? Unit { get; set; }
        public decimal Quantity { get; set; }
        public decimal Value { get; set; }

        /// <summary>Lot references behind this item, kept as the opening
        /// balance's note.</summary>
        public string? LotRefs { get; set; }

        /// <summary>One of <see cref="OpeningStockRowStatus"/>.</summary>
        public string Status { get; set; } = OpeningStockRowStatus.WillCreate;

        /// <summary>Item type this row resolved to, when it matched one.</summary>
        public int? ItemTypeId { get; set; }
        public string? MatchedName { get; set; }

        /// <summary>Choices offered on an <c>ambiguous</c> row.</summary>
        public List<OpeningStockCandidateDto> Candidates { get; set; } = new();

        public List<string> Messages { get; set; } = new();
    }

    public class OpeningStockPreviewDto
    {
        public string FileName { get; set; } = "";
        public string FileSha256 { get; set; } = "";
        public long FileSizeBytes { get; set; }
        public int? ImportProfileId { get; set; }
        public int? ProfileVersion { get; set; }

        public List<OpeningStockRowDto> Rows { get; set; } = new();

        /// <summary>Counts per status, for the summary line above the table.</summary>
        public Dictionary<string, int> StatusCounts { get; set; } = new();

        public decimal TotalQuantity { get; set; }
        public decimal TotalValue { get; set; }

        /// <summary>Source rows read, before grouping. Differs from
        /// <c>Rows.Count</c> exactly when an item spans several lots, which is
        /// worth showing rather than hiding.</summary>
        public int SourceRowCount { get; set; }

        /// <summary>Commit is refused while this is non-empty.</summary>
        public List<string> BlockingErrors { get; set; } = new();
        public List<string> Warnings { get; set; } = new();

        public bool CanCommit => BlockingErrors.Count == 0 && Rows.Count > 0;
    }

    /// <summary>One reviewed row, as the operator confirmed it.</summary>
    public class OpeningStockCommitRowDto
    {
        public string ItemName { get; set; } = "";
        public string? HsCode { get; set; }
        public bool IsHsCodePartial { get; set; }
        public string? Unit { get; set; }
        public decimal Quantity { get; set; }
        public decimal Value { get; set; }
        public string? LotRefs { get; set; }

        /// <summary>Set to reuse that item type; null to create a new one. On an
        /// ambiguous row this carries the operator's choice.</summary>
        public int? ItemTypeId { get; set; }
    }

    /// <summary>
    /// Commit takes the REVIEWED rows, not the file again — what the operator
    /// approved on screen is exactly what gets written. The file's hash comes
    /// along so the import can still be recorded and de-duplicated.
    /// </summary>
    public class OpeningStockCommitDto
    {
        public int CompanyId { get; set; }
        public int? ImportProfileId { get; set; }
        public int? ProfileVersion { get; set; }

        public string FileSha256 { get; set; } = "";
        public string FileName { get; set; } = "";
        public long FileSizeBytes { get; set; }

        /// <summary>Date the opening quantities are "as at" — normally the first
        /// day of the new financial year.</summary>
        public DateTime AsOfDate { get; set; }

        /// <summary>
        /// Post the total value as the Inventory account's opening balance.
        /// Default true; an operator who has already entered a trial balance by
        /// hand turns it off so the figure is not counted twice.
        /// </summary>
        public bool PostInventoryValue { get; set; } = true;

        /// <summary>
        /// Switch the company to tracking every item type as inventory. Default
        /// true for an onboarding import; off when adding stock to a company
        /// already running its own policy.
        /// </summary>
        public bool EnableInventoryTracking { get; set; } = true;

        public List<OpeningStockCommitRowDto> Rows { get; set; } = new();
    }

    public class OpeningStockCommitResultDto
    {
        public int ImportRunId { get; set; }
        public int ItemTypesCreated { get; set; }
        public int ItemTypesUpdated { get; set; }
        public int OpeningBalancesWritten { get; set; }
        public int RowsSkippedAlreadyImported { get; set; }
        public decimal TotalQuantity { get; set; }
        public decimal InventoryValuePosted { get; set; }
        public bool InventoryTrackingEnabled { get; set; }
        public List<string> Messages { get; set; } = new();
    }
}
