using Microsoft.EntityFrameworkCore;
using MyApp.Api.Data;

namespace MyApp.Api.Helpers
{
    /// <summary>
    /// Which companies an <see cref="Models.ItemType"/> belongs to (CLAUDE.md
    /// §5b-2b). The catalog has no CompanyId -- the HS tariff master lives in it
    /// -- so membership is DERIVED: the company's registrations plus every table
    /// that references an item. Adding a document type that carries an
    /// ItemTypeId means adding a leg here, or its items vanish from their
    /// owner's picker.
    ///
    /// One definition for the pickers (ItemTypeRepository), the by-id endpoints
    /// and the write paths, so "may see" and "may change" cannot drift apart.
    /// </summary>
    public static class ItemTypeMembership
    {
        /// <summary>
        /// The item ids the given companies hold. An IQueryable on purpose: it
        /// composes into the caller's query as one IN (SELECT ...).
        /// </summary>
        public static IQueryable<int> CompanyItemTypeIds(AppDbContext db, List<int> companyIds)
        {
            // The company's own registrations -- Mode is irrelevant here; a
            // Default row means "this company has this item on its books",
            // which is exactly the question being asked.
            var registered = db.CompanyItemTypeSettings
                .Where(s => companyIds.Contains(s.CompanyId)).Select(s => s.ItemTypeId);

            var openings = db.OpeningStockBalances
                .Where(o => companyIds.Contains(o.CompanyId)).Select(o => o.ItemTypeId);
            var movements = db.StockMovements
                .Where(m => companyIds.Contains(m.CompanyId)).Select(m => m.ItemTypeId);

            var invoiceLines = db.InvoiceItems
                .Where(ii => ii.ItemTypeId != null && companyIds.Contains(ii.Invoice!.CompanyId))
                .Select(ii => ii.ItemTypeId!.Value);
            // The filed book of an overlay company can classify a line
            // differently from the bill, so it is a separate source.
            var adjustments =
                from a in db.InvoiceItemAdjustments
                join i in db.Invoices on a.InvoiceId equals i.Id
                where a.AdjustedItemTypeId != null && companyIds.Contains(i.CompanyId)
                select a.AdjustedItemTypeId!.Value;

            var purchaseLines = db.PurchaseItems
                .Where(pi => pi.ItemTypeId != null && companyIds.Contains(pi.PurchaseBill!.CompanyId))
                .Select(pi => pi.ItemTypeId!.Value);
            var debitNoteLines = db.PurchaseDebitNoteItems
                .Where(d => d.ItemTypeId != null && companyIds.Contains(d.PurchaseDebitNote!.CompanyId))
                .Select(d => d.ItemTypeId!.Value);
            var receiptLines = db.GoodsReceiptItems
                .Where(g => g.ItemTypeId != null && companyIds.Contains(g.GoodsReceipt!.CompanyId))
                .Select(g => g.ItemTypeId!.Value);
            var challanLines = db.DeliveryItems
                .Where(d => d.ItemTypeId != null && companyIds.Contains(d.DeliveryChallan!.CompanyId))
                .Select(d => d.ItemTypeId!.Value);
            var orderLines = db.SalesOrderItems
                .Where(s => s.ItemTypeId != null && companyIds.Contains(s.SalesOrder!.CompanyId))
                .Select(s => s.ItemTypeId!.Value);
            var quoteLines = db.SalesQuoteItems
                .Where(s => s.ItemTypeId != null && companyIds.Contains(s.SalesQuote!.CompanyId))
                .Select(s => s.ItemTypeId!.Value);
            // A GD costing line that verified against an item makes it the
            // importer's own, even before any stock or document names it.
            var gdLines = db.ImportConsignmentLines
                .Where(l => l.ItemTypeId != null && companyIds.Contains(l.ImportConsignment.CompanyId))
                .Select(l => l.ItemTypeId!.Value);

            return registered
                .Union(openings).Union(movements)
                .Union(invoiceLines).Union(adjustments)
                .Union(purchaseLines).Union(debitNoteLines).Union(receiptLines)
                .Union(challanLines).Union(orderLines).Union(quoteLines)
                .Union(gdLines);
        }

        /// <summary>
        /// True when a caller who can reach <paramref name="companyIds"/> may SEE
        /// the item: one of those companies holds it, or it is an un-adopted HS
        /// tariff placeholder (installation reference data, visible to all).
        /// </summary>
        public static async Task<bool> IsVisibleAsync(AppDbContext db, int itemTypeId, IEnumerable<int> companyIds)
        {
            var ids = companyIds.Where(i => i > 0).Distinct().ToList();
            var placeholder = await db.ItemTypes.AsNoTracking()
                .AnyAsync(it => it.Id == itemTypeId && it.IsAutoGenerated && !it.IsFavorite);
            if (placeholder) return true;
            if (ids.Count == 0) return false;
            return await CompanyItemTypeIds(db, ids).AnyAsync(id => id == itemTypeId);
        }

        /// <summary>
        /// True when a company OUTSIDE <paramref name="companyIds"/> holds the
        /// item. The catalog row is shared, so renaming, reclassifying or
        /// deleting it would change that other company's books -- the change is
        /// refused and the company's own name (DisplayName) is the way to differ.
        /// A caller who can reach every company (the seed admin) is never
        /// "outside" anyone.
        /// </summary>
        public static async Task<bool> IsHeldOutsideAsync(AppDbContext db, int itemTypeId, IEnumerable<int> companyIds)
        {
            var mine = companyIds.ToHashSet();
            var others = (await db.Companies.AsNoTracking().Select(c => c.Id).ToListAsync())
                .Where(id => !mine.Contains(id)).ToList();
            if (others.Count == 0) return false;
            return await CompanyItemTypeIds(db, others).AnyAsync(id => id == itemTypeId);
        }
    }
}
