// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyApp.Api.Data;

#nullable disable

namespace MyApp.Api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260424201044_AddRbacTables")]
    partial class AddRbacTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MyApp.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ExceptionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QueryString")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestBody")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StackTrace")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StatusCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Timestamp");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("MyApp.Api.Models.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FbrProvinceCode")
                        .HasColumnType("int");

                    b.Property<string>("NTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistrationType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("MyApp.Api.Models.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrandName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNIC")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CurrentChallanNumber")
                        .HasColumnType("int");

                    b.Property<int>("CurrentInvoiceNumber")
                        .HasColumnType("int");

                    b.Property<string>("FbrBusinessActivity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrDefaultPaymentModeRegistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrDefaultPaymentModeUnregistered")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrDefaultSaleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrDefaultUOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrEnvironment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FbrProvinceCode")
                        .HasColumnType("int");

                    b.Property<string>("FbrSector")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullAddress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvoiceNumberPrefix")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LogoPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NTN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("STRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("StartingChallanNumber")
                        .HasColumnType("int");

                    b.Property<int>("StartingInvoiceNumber")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("MyApp.Api.Models.DeliveryChallan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ChallanNumber")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<bool>("IsImported")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PoDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PoNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Site")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("Pending");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("InvoiceId");

                    b.ToTable("DeliveryChallans");
                });

            modelBuilder.Entity("MyApp.Api.Models.DeliveryItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeliveryChallanId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryChallanId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("DeliveryItems");
                });

            modelBuilder.Entity("MyApp.Api.Models.FbrLookup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FbrLookups");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Province",
                            Code = "7",
                            IsActive = true,
                            Label = "Punjab",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 2,
                            Category = "Province",
                            Code = "8",
                            IsActive = true,
                            Label = "Sindh",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 3,
                            Category = "Province",
                            Code = "9",
                            IsActive = true,
                            Label = "KPK",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 4,
                            Category = "Province",
                            Code = "10",
                            IsActive = true,
                            Label = "Balochistan",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 5,
                            Category = "Province",
                            Code = "11",
                            IsActive = true,
                            Label = "Islamabad",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 6,
                            Category = "Province",
                            Code = "12",
                            IsActive = true,
                            Label = "AJK",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 7,
                            Category = "Province",
                            Code = "13",
                            IsActive = true,
                            Label = "GB",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 8,
                            Category = "BusinessActivity",
                            Code = "Manufacturer",
                            IsActive = true,
                            Label = "Manufacturer",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 9,
                            Category = "BusinessActivity",
                            Code = "Importer",
                            IsActive = true,
                            Label = "Importer",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 10,
                            Category = "BusinessActivity",
                            Code = "Distributor",
                            IsActive = true,
                            Label = "Distributor",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 11,
                            Category = "BusinessActivity",
                            Code = "Wholesaler",
                            IsActive = true,
                            Label = "Wholesaler",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 12,
                            Category = "BusinessActivity",
                            Code = "Exporter",
                            IsActive = true,
                            Label = "Exporter",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 13,
                            Category = "BusinessActivity",
                            Code = "Retailer",
                            IsActive = true,
                            Label = "Retailer",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 14,
                            Category = "BusinessActivity",
                            Code = "Service Provider",
                            IsActive = true,
                            Label = "Service Provider",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 15,
                            Category = "BusinessActivity",
                            Code = "Other",
                            IsActive = true,
                            Label = "Other",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 16,
                            Category = "Sector",
                            Code = "All Other Sectors",
                            IsActive = true,
                            Label = "All Other Sectors",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 17,
                            Category = "Sector",
                            Code = "Steel",
                            IsActive = true,
                            Label = "Steel",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 18,
                            Category = "Sector",
                            Code = "FMCG",
                            IsActive = true,
                            Label = "FMCG",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 19,
                            Category = "Sector",
                            Code = "Textile",
                            IsActive = true,
                            Label = "Textile",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 20,
                            Category = "Sector",
                            Code = "Telecom",
                            IsActive = true,
                            Label = "Telecom",
                            SortOrder = 5
                        },
                        new
                        {
                            Id = 21,
                            Category = "Sector",
                            Code = "Petroleum",
                            IsActive = true,
                            Label = "Petroleum",
                            SortOrder = 6
                        },
                        new
                        {
                            Id = 22,
                            Category = "Sector",
                            Code = "Electricity Distribution",
                            IsActive = true,
                            Label = "Electricity Distribution",
                            SortOrder = 7
                        },
                        new
                        {
                            Id = 23,
                            Category = "Sector",
                            Code = "Gas Distribution",
                            IsActive = true,
                            Label = "Gas Distribution",
                            SortOrder = 8
                        },
                        new
                        {
                            Id = 24,
                            Category = "Sector",
                            Code = "Services",
                            IsActive = true,
                            Label = "Services",
                            SortOrder = 9
                        },
                        new
                        {
                            Id = 25,
                            Category = "Sector",
                            Code = "Automobile",
                            IsActive = true,
                            Label = "Automobile",
                            SortOrder = 10
                        },
                        new
                        {
                            Id = 26,
                            Category = "Sector",
                            Code = "CNG Stations",
                            IsActive = true,
                            Label = "CNG Stations",
                            SortOrder = 11
                        },
                        new
                        {
                            Id = 27,
                            Category = "Sector",
                            Code = "Pharmaceuticals",
                            IsActive = true,
                            Label = "Pharmaceuticals",
                            SortOrder = 12
                        },
                        new
                        {
                            Id = 28,
                            Category = "Sector",
                            Code = "Wholesale / Retails",
                            IsActive = true,
                            Label = "Wholesale / Retails",
                            SortOrder = 13
                        },
                        new
                        {
                            Id = 29,
                            Category = "RegistrationType",
                            Code = "Registered",
                            IsActive = true,
                            Label = "Registered",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 30,
                            Category = "RegistrationType",
                            Code = "Unregistered",
                            IsActive = true,
                            Label = "Unregistered",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 31,
                            Category = "RegistrationType",
                            Code = "FTN",
                            IsActive = true,
                            Label = "FTN",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 32,
                            Category = "RegistrationType",
                            Code = "CNIC",
                            IsActive = true,
                            Label = "CNIC",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 33,
                            Category = "Environment",
                            Code = "sandbox",
                            IsActive = true,
                            Label = "Sandbox",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 34,
                            Category = "Environment",
                            Code = "production",
                            IsActive = true,
                            Label = "Production",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 35,
                            Category = "DocumentType",
                            Code = "4",
                            IsActive = true,
                            Label = "Sale Invoice",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 36,
                            Category = "DocumentType",
                            Code = "9",
                            IsActive = true,
                            Label = "Debit Note",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 37,
                            Category = "DocumentType",
                            Code = "10",
                            IsActive = true,
                            Label = "Credit Note",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 38,
                            Category = "PaymentMode",
                            Code = "Cash",
                            IsActive = true,
                            Label = "Cash",
                            SortOrder = 1
                        },
                        new
                        {
                            Id = 39,
                            Category = "PaymentMode",
                            Code = "Credit",
                            IsActive = true,
                            Label = "Credit",
                            SortOrder = 2
                        },
                        new
                        {
                            Id = 40,
                            Category = "PaymentMode",
                            Code = "Bank Transfer",
                            IsActive = true,
                            Label = "Bank Transfer",
                            SortOrder = 3
                        },
                        new
                        {
                            Id = 41,
                            Category = "PaymentMode",
                            Code = "Cheque",
                            IsActive = true,
                            Label = "Cheque",
                            SortOrder = 4
                        },
                        new
                        {
                            Id = 42,
                            Category = "PaymentMode",
                            Code = "Online",
                            IsActive = true,
                            Label = "Online",
                            SortOrder = 5
                        });
                });

            modelBuilder.Entity("MyApp.Api.Models.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AmountInWords")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DocumentType")
                        .HasColumnType("int");

                    b.Property<string>("FbrErrorMessage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrIRN")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrInvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FbrStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FbrSubmittedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GSTAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GSTRate")
                        .HasPrecision(5, 2)
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("GrandTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("InvoiceNumber")
                        .HasColumnType("int");

                    b.Property<bool>("IsFbrExcluded")
                        .HasColumnType("bit");

                    b.Property<string>("PaymentMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId", "InvoiceNumber");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("MyApp.Api.Models.InvoiceItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("DeliveryItemId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FbrUOMId")
                        .HasColumnType("int");

                    b.Property<decimal?>("FixedNotifiedValueOrRetailPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<int?>("ItemTypeId")
                        .HasColumnType("int");

                    b.Property<string>("ItemTypeName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("LineTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<int?>("RateId")
                        .HasColumnType("int");

                    b.Property<string>("SaleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SroItemSerialNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SroScheduleNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryItemId");

                    b.HasIndex("InvoiceId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("InvoiceItems");
                });

            modelBuilder.Entity("MyApp.Api.Models.ItemDescription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("FbrUOMId")
                        .HasColumnType("int");

                    b.Property<string>("HSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SaleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ItemDescriptions");
                });

            modelBuilder.Entity("MyApp.Api.Models.ItemType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FbrDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("FbrUOMId")
                        .HasColumnType("int");

                    b.Property<string>("HSCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFavorite")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SaleType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UOM")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsageCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("ItemTypes");
                });

            modelBuilder.Entity("MyApp.Api.Models.MergeField", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FieldExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("TemplateType", "FieldExpression")
                        .IsUnique();

                    b.ToTable("MergeFields");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Company",
                            FieldExpression = "{{companyBrandName}}",
                            Label = "Company Brand Name",
                            SortOrder = 1,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Company",
                            FieldExpression = "{{companyLogoPath}}",
                            Label = "Company Logo URL",
                            SortOrder = 2,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Company",
                            FieldExpression = "{{{nl2br companyAddress}}}",
                            Label = "Company Address (with line breaks)",
                            SortOrder = 3,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Company",
                            FieldExpression = "{{{nl2br companyPhone}}}",
                            Label = "Company Phone (with line breaks)",
                            SortOrder = 4,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 5,
                            Category = "Document",
                            FieldExpression = "{{challanNumber}}",
                            Label = "Challan Number",
                            SortOrder = 10,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 6,
                            Category = "Document",
                            FieldExpression = "{{fmtDate deliveryDate}}",
                            Label = "Delivery Date",
                            SortOrder = 11,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 7,
                            Category = "Document",
                            FieldExpression = "{{poNumber}}",
                            Label = "PO Number",
                            SortOrder = 12,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 8,
                            Category = "Document",
                            FieldExpression = "{{fmtDate poDate}}",
                            Label = "PO Date",
                            SortOrder = 13,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 9,
                            Category = "Client",
                            FieldExpression = "{{clientName}}",
                            Label = "Client Name",
                            SortOrder = 20,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 10,
                            Category = "Client",
                            FieldExpression = "{{clientAddress}}",
                            Label = "Client Address",
                            SortOrder = 21,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 11,
                            Category = "Client",
                            FieldExpression = "{{clientSite}}",
                            Label = "Client Site",
                            SortOrder = 22,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 12,
                            Category = "Items",
                            FieldExpression = "{{items.length}}",
                            Label = "Item Count",
                            SortOrder = 30,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 13,
                            Category = "Items",
                            FieldExpression = "{{#each items}}",
                            Label = "Loop: Items Start",
                            SortOrder = 31,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 14,
                            Category = "Items",
                            FieldExpression = "{{/each}}",
                            Label = "Loop: End",
                            SortOrder = 32,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 15,
                            Category = "Items",
                            FieldExpression = "{{this.quantity}}",
                            Label = "Item Quantity (in loop)",
                            SortOrder = 33,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 16,
                            Category = "Items",
                            FieldExpression = "{{this.description}}",
                            Label = "Item Description (in loop)",
                            SortOrder = 34,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 17,
                            Category = "Conditionals",
                            FieldExpression = "{{#if companyLogoPath}}",
                            Label = "If: Has Logo",
                            SortOrder = 40,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 18,
                            Category = "Conditionals",
                            FieldExpression = "{{#if companyAddress}}",
                            Label = "If: Has Address",
                            SortOrder = 41,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 19,
                            Category = "Conditionals",
                            FieldExpression = "{{#if companyPhone}}",
                            Label = "If: Has Phone",
                            SortOrder = 42,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 20,
                            Category = "Conditionals",
                            FieldExpression = "{{#if poNumber}}",
                            Label = "If: Has PO Number",
                            SortOrder = 43,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 21,
                            Category = "Conditionals",
                            FieldExpression = "{{#if poDate}}",
                            Label = "If: Has PO Date",
                            SortOrder = 44,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 22,
                            Category = "Conditionals",
                            FieldExpression = "{{#if clientSite}}",
                            Label = "If: Has Client Site",
                            SortOrder = 45,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 23,
                            Category = "Conditionals",
                            FieldExpression = "{{else}}",
                            Label = "Else",
                            SortOrder = 46,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 24,
                            Category = "Conditionals",
                            FieldExpression = "{{/if}}",
                            Label = "End If",
                            SortOrder = 47,
                            TemplateType = "Challan"
                        },
                        new
                        {
                            Id = 25,
                            Category = "Company",
                            FieldExpression = "{{companyBrandName}}",
                            Label = "Company Brand Name",
                            SortOrder = 1,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 26,
                            Category = "Company",
                            FieldExpression = "{{companyLogoPath}}",
                            Label = "Company Logo URL",
                            SortOrder = 2,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 27,
                            Category = "Company",
                            FieldExpression = "{{{nl2br companyAddress}}}",
                            Label = "Company Address (with line breaks)",
                            SortOrder = 3,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 28,
                            Category = "Company",
                            FieldExpression = "{{{nl2br companyPhone}}}",
                            Label = "Company Phone (with line breaks)",
                            SortOrder = 4,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 29,
                            Category = "Company",
                            FieldExpression = "{{companyNTN}}",
                            Label = "Company NTN",
                            SortOrder = 5,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 30,
                            Category = "Company",
                            FieldExpression = "{{companySTRN}}",
                            Label = "Company STRN",
                            SortOrder = 6,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 31,
                            Category = "Document",
                            FieldExpression = "{{invoiceNumber}}",
                            Label = "Invoice/Bill Number",
                            SortOrder = 10,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 32,
                            Category = "Document",
                            FieldExpression = "{{fmtDate date}}",
                            Label = "Invoice Date",
                            SortOrder = 11,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 33,
                            Category = "Document",
                            FieldExpression = "{{join challanNumbers}}",
                            Label = "Challan Numbers (comma-separated)",
                            SortOrder = 12,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 34,
                            Category = "Document",
                            FieldExpression = "{{joinDates challanDates}}",
                            Label = "Challan Dates (comma-separated)",
                            SortOrder = 13,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 35,
                            Category = "Document",
                            FieldExpression = "{{poNumber}}",
                            Label = "PO Number",
                            SortOrder = 14,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 36,
                            Category = "Document",
                            FieldExpression = "{{fmtDate poDate}}",
                            Label = "PO Date",
                            SortOrder = 15,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 37,
                            Category = "Client",
                            FieldExpression = "{{clientName}}",
                            Label = "Client Name",
                            SortOrder = 20,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 38,
                            Category = "Client",
                            FieldExpression = "{{clientAddress}}",
                            Label = "Client Address",
                            SortOrder = 21,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 39,
                            Category = "Client",
                            FieldExpression = "{{concernDepartment}}",
                            Label = "Concern Department",
                            SortOrder = 22,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 40,
                            Category = "Client",
                            FieldExpression = "{{clientNTN}}",
                            Label = "Client NTN",
                            SortOrder = 23,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 41,
                            Category = "Client",
                            FieldExpression = "{{clientSTRN}}",
                            Label = "Client STRN/GST",
                            SortOrder = 24,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 42,
                            Category = "Totals",
                            FieldExpression = "{{fmt subtotal}}",
                            Label = "Subtotal (formatted)",
                            SortOrder = 30,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 43,
                            Category = "Totals",
                            FieldExpression = "{{gstRate}}",
                            Label = "GST Rate %",
                            SortOrder = 31,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 44,
                            Category = "Totals",
                            FieldExpression = "{{fmt gstAmount}}",
                            Label = "GST Amount (formatted)",
                            SortOrder = 32,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 45,
                            Category = "Totals",
                            FieldExpression = "{{fmt grandTotal}}",
                            Label = "Grand Total (formatted)",
                            SortOrder = 33,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 46,
                            Category = "Totals",
                            FieldExpression = "{{amountInWords}}",
                            Label = "Amount In Words",
                            SortOrder = 34,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 47,
                            Category = "Items",
                            FieldExpression = "{{#each items}}",
                            Label = "Loop: Items Start",
                            SortOrder = 40,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 48,
                            Category = "Items",
                            FieldExpression = "{{/each}}",
                            Label = "Loop: End",
                            SortOrder = 41,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 49,
                            Category = "Items",
                            FieldExpression = "{{this.sNo}}",
                            Label = "Item S# (in loop)",
                            SortOrder = 42,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 50,
                            Category = "Items",
                            FieldExpression = "{{this.quantity}}",
                            Label = "Item Quantity (in loop)",
                            SortOrder = 43,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 51,
                            Category = "Items",
                            FieldExpression = "{{this.description}}",
                            Label = "Item Description (in loop)",
                            SortOrder = 44,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 52,
                            Category = "Items",
                            FieldExpression = "{{this.itemTypeName}}",
                            Label = "Item Type Name (in loop)",
                            SortOrder = 45,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 53,
                            Category = "Items",
                            FieldExpression = "{{fmt this.unitPrice}}",
                            Label = "Unit Price (in loop)",
                            SortOrder = 46,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 54,
                            Category = "Items",
                            FieldExpression = "{{fmt this.lineTotal}}",
                            Label = "Line Total (in loop)",
                            SortOrder = 47,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 55,
                            Category = "Conditionals",
                            FieldExpression = "{{#if companyLogoPath}}",
                            Label = "If: Has Logo",
                            SortOrder = 50,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 56,
                            Category = "Conditionals",
                            FieldExpression = "{{#if clientNTN}}",
                            Label = "If: Has Client NTN",
                            SortOrder = 51,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 57,
                            Category = "Conditionals",
                            FieldExpression = "{{#if clientSTRN}}",
                            Label = "If: Has Client STRN",
                            SortOrder = 52,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 58,
                            Category = "Conditionals",
                            FieldExpression = "{{#if poNumber}}",
                            Label = "If: Has PO Number",
                            SortOrder = 53,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 59,
                            Category = "Conditionals",
                            FieldExpression = "{{#if poDate}}",
                            Label = "If: Has PO Date",
                            SortOrder = 54,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 60,
                            Category = "Conditionals",
                            FieldExpression = "{{else}}",
                            Label = "Else",
                            SortOrder = 55,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 61,
                            Category = "Conditionals",
                            FieldExpression = "{{/if}}",
                            Label = "End If",
                            SortOrder = 56,
                            TemplateType = "Bill"
                        },
                        new
                        {
                            Id = 62,
                            Category = "Supplier",
                            FieldExpression = "{{supplierName}}",
                            Label = "Supplier Name",
                            SortOrder = 1,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 63,
                            Category = "Supplier",
                            FieldExpression = "{{{nl2br supplierAddress}}}",
                            Label = "Supplier Address (with line breaks)",
                            SortOrder = 2,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 64,
                            Category = "Supplier",
                            FieldExpression = "{{{nl2br supplierPhone}}}",
                            Label = "Supplier Phone (with line breaks)",
                            SortOrder = 3,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 65,
                            Category = "Supplier",
                            FieldExpression = "{{supplierNTN}}",
                            Label = "Supplier NTN",
                            SortOrder = 4,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 66,
                            Category = "Supplier",
                            FieldExpression = "{{supplierSTRN}}",
                            Label = "Supplier STRN",
                            SortOrder = 5,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 67,
                            Category = "Buyer",
                            FieldExpression = "{{buyerName}}",
                            Label = "Buyer Name",
                            SortOrder = 10,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 68,
                            Category = "Buyer",
                            FieldExpression = "{{{nl2br buyerAddress}}}",
                            Label = "Buyer Address (with line breaks)",
                            SortOrder = 11,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 69,
                            Category = "Buyer",
                            FieldExpression = "{{buyerPhone}}",
                            Label = "Buyer Phone",
                            SortOrder = 12,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 70,
                            Category = "Buyer",
                            FieldExpression = "{{buyerNTN}}",
                            Label = "Buyer NTN",
                            SortOrder = 13,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 71,
                            Category = "Buyer",
                            FieldExpression = "{{buyerSTRN}}",
                            Label = "Buyer STRN",
                            SortOrder = 14,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 72,
                            Category = "Document",
                            FieldExpression = "{{invoiceNumber}}",
                            Label = "Invoice Number",
                            SortOrder = 20,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 73,
                            Category = "Document",
                            FieldExpression = "{{fmtDate date}}",
                            Label = "Invoice Date",
                            SortOrder = 21,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 74,
                            Category = "Document",
                            FieldExpression = "{{join challanNumbers}}",
                            Label = "Challan Numbers",
                            SortOrder = 22,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 75,
                            Category = "Document",
                            FieldExpression = "{{poNumber}}",
                            Label = "PO Number",
                            SortOrder = 23,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 76,
                            Category = "Totals",
                            FieldExpression = "{{gstRate}}",
                            Label = "GST Rate %",
                            SortOrder = 30,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 77,
                            Category = "Totals",
                            FieldExpression = "{{fmtDec subtotal}}",
                            Label = "Subtotal (2 decimals)",
                            SortOrder = 31,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 78,
                            Category = "Totals",
                            FieldExpression = "{{fmtDec gstAmount}}",
                            Label = "GST Amount (2 decimals)",
                            SortOrder = 32,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 79,
                            Category = "Totals",
                            FieldExpression = "{{fmtDec grandTotal}}",
                            Label = "Grand Total (2 decimals)",
                            SortOrder = 33,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 80,
                            Category = "Totals",
                            FieldExpression = "{{amountInWords}}",
                            Label = "Amount In Words",
                            SortOrder = 34,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 81,
                            Category = "Items",
                            FieldExpression = "{{#each items}}",
                            Label = "Loop: Items Start",
                            SortOrder = 40,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 82,
                            Category = "Items",
                            FieldExpression = "{{/each}}",
                            Label = "Loop: End",
                            SortOrder = 41,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 83,
                            Category = "Items",
                            FieldExpression = "{{this.quantity}}",
                            Label = "Item Quantity (in loop)",
                            SortOrder = 42,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 84,
                            Category = "Items",
                            FieldExpression = "{{this.uom}}",
                            Label = "Item UOM (in loop)",
                            SortOrder = 43,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 85,
                            Category = "Items",
                            FieldExpression = "{{this.description}}",
                            Label = "Item Description (in loop)",
                            SortOrder = 44,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 86,
                            Category = "Items",
                            FieldExpression = "{{fmtDec this.valueExclTax}}",
                            Label = "Value Excl Tax (in loop)",
                            SortOrder = 45,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 87,
                            Category = "Items",
                            FieldExpression = "{{this.gstRate}}",
                            Label = "GST Rate % (in loop)",
                            SortOrder = 46,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 88,
                            Category = "Items",
                            FieldExpression = "{{fmtDec this.gstAmount}}",
                            Label = "GST Amount (in loop)",
                            SortOrder = 47,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 89,
                            Category = "Items",
                            FieldExpression = "{{fmtDec this.totalInclTax}}",
                            Label = "Total Incl Tax (in loop)",
                            SortOrder = 48,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 90,
                            Category = "Conditionals",
                            FieldExpression = "{{#if supplierAddress}}",
                            Label = "If: Has Supplier Address",
                            SortOrder = 50,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 91,
                            Category = "Conditionals",
                            FieldExpression = "{{#if supplierPhone}}",
                            Label = "If: Has Supplier Phone",
                            SortOrder = 51,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 92,
                            Category = "Conditionals",
                            FieldExpression = "{{#if supplierSTRN}}",
                            Label = "If: Has Supplier STRN",
                            SortOrder = 52,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 93,
                            Category = "Conditionals",
                            FieldExpression = "{{#if supplierNTN}}",
                            Label = "If: Has Supplier NTN",
                            SortOrder = 53,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 94,
                            Category = "Conditionals",
                            FieldExpression = "{{#if buyerAddress}}",
                            Label = "If: Has Buyer Address",
                            SortOrder = 54,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 95,
                            Category = "Conditionals",
                            FieldExpression = "{{#if buyerPhone}}",
                            Label = "If: Has Buyer Phone",
                            SortOrder = 55,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 96,
                            Category = "Conditionals",
                            FieldExpression = "{{#if buyerSTRN}}",
                            Label = "If: Has Buyer STRN",
                            SortOrder = 56,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 97,
                            Category = "Conditionals",
                            FieldExpression = "{{#if buyerNTN}}",
                            Label = "If: Has Buyer NTN",
                            SortOrder = 57,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 98,
                            Category = "Conditionals",
                            FieldExpression = "{{else}}",
                            Label = "Else",
                            SortOrder = 58,
                            TemplateType = "TaxInvoice"
                        },
                        new
                        {
                            Id = 99,
                            Category = "Conditionals",
                            FieldExpression = "{{/if}}",
                            Label = "End If",
                            SortOrder = 59,
                            TemplateType = "TaxInvoice"
                        });
                });

            modelBuilder.Entity("MyApp.Api.Models.POFormat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClientId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CurrentVersion")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("KeywordSignature")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RuleSetJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SignatureHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("SignatureHash");

                    b.HasIndex("CompanyId", "ClientId");

                    b.HasIndex("CompanyId", "IsActive");

                    b.ToTable("POFormats");
                });

            modelBuilder.Entity("MyApp.Api.Models.POFormatVersion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ChangeNote")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POFormatId")
                        .HasColumnType("int");

                    b.Property<string>("RuleSetJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("POFormatId", "Version")
                        .IsUnique();

                    b.ToTable("POFormatVersions");
                });

            modelBuilder.Entity("MyApp.Api.Models.POGoldenSample", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExpectedJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("POFormatId")
                        .HasColumnType("int");

                    b.Property<byte[]>("PdfBlob")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("RawText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("Id");

                    b.HasIndex("POFormatId", "Status");

                    b.ToTable("POGoldenSamples");
                });

            modelBuilder.Entity("MyApp.Api.Models.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Module")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("MyApp.Api.Models.PrintTemplate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("EditorMode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ExcelTemplatePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HtmlContent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateType")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "TemplateType")
                        .IsUnique();

                    b.ToTable("PrintTemplates");
                });

            modelBuilder.Entity("MyApp.Api.Models.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsSystemRole")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("MyApp.Api.Models.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<int>("PermissionId")
                        .HasColumnType("int");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions");
                });

            modelBuilder.Entity("MyApp.Api.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Units");
                });

            modelBuilder.Entity("MyApp.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AvatarPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FullName = "Administrator",
                            PasswordHash = "$2a$11$ITxobMb6Kk7r4cjBAN3tF.U2x5q/PpaueP/1dvUSr6V0N5z724cuu",
                            Role = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("MyApp.Api.Models.UserRole", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("AssignedByUserId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("MyApp.Api.Models.Client", b =>
                {
                    b.HasOne("MyApp.Api.Models.Company", "Company")
                        .WithMany("Clients")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MyApp.Api.Models.DeliveryChallan", b =>
                {
                    b.HasOne("MyApp.Api.Models.Client", "Client")
                        .WithMany("DeliveryChallans")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Api.Models.Company", "Company")
                        .WithMany("DeliveryChallans")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Api.Models.Invoice", "Invoice")
                        .WithMany("DeliveryChallans")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Client");

                    b.Navigation("Company");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("MyApp.Api.Models.DeliveryItem", b =>
                {
                    b.HasOne("MyApp.Api.Models.DeliveryChallan", "DeliveryChallan")
                        .WithMany("Items")
                        .HasForeignKey("DeliveryChallanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Api.Models.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("DeliveryChallan");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("MyApp.Api.Models.Invoice", b =>
                {
                    b.HasOne("MyApp.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyApp.Api.Models.Company", "Company")
                        .WithMany("Invoices")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MyApp.Api.Models.InvoiceItem", b =>
                {
                    b.HasOne("MyApp.Api.Models.DeliveryItem", "DeliveryItem")
                        .WithMany()
                        .HasForeignKey("DeliveryItemId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyApp.Api.Models.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Api.Models.ItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId");

                    b.Navigation("DeliveryItem");

                    b.Navigation("Invoice");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("MyApp.Api.Models.POFormat", b =>
                {
                    b.HasOne("MyApp.Api.Models.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("MyApp.Api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MyApp.Api.Models.POFormatVersion", b =>
                {
                    b.HasOne("MyApp.Api.Models.POFormat", "POFormat")
                        .WithMany()
                        .HasForeignKey("POFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POFormat");
                });

            modelBuilder.Entity("MyApp.Api.Models.POGoldenSample", b =>
                {
                    b.HasOne("MyApp.Api.Models.POFormat", "POFormat")
                        .WithMany()
                        .HasForeignKey("POFormatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("POFormat");
                });

            modelBuilder.Entity("MyApp.Api.Models.PrintTemplate", b =>
                {
                    b.HasOne("MyApp.Api.Models.Company", "Company")
                        .WithMany()
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("MyApp.Api.Models.RolePermission", b =>
                {
                    b.HasOne("MyApp.Api.Models.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Api.Models.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("MyApp.Api.Models.UserRole", b =>
                {
                    b.HasOne("MyApp.Api.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyApp.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyApp.Api.Models.Client", b =>
                {
                    b.Navigation("DeliveryChallans");
                });

            modelBuilder.Entity("MyApp.Api.Models.Company", b =>
                {
                    b.Navigation("Clients");

                    b.Navigation("DeliveryChallans");

                    b.Navigation("Invoices");
                });

            modelBuilder.Entity("MyApp.Api.Models.DeliveryChallan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyApp.Api.Models.Invoice", b =>
                {
                    b.Navigation("DeliveryChallans");

                    b.Navigation("Items");
                });

            modelBuilder.Entity("MyApp.Api.Models.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("MyApp.Api.Models.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
