using Microsoft.EntityFrameworkCore;
using MyApp.Api.Data;
using MyApp.Api.Models;
using MyApp.Api.Repositories.Interfaces;

namespace MyApp.Api.Repositories.Implementations
{
    public class ItemTypeRepository : IItemTypeRepository
    {
        private readonly AppDbContext _context;

        public ItemTypeRepository(AppDbContext context)
        {
            _context = context;
        }

        public Task<List<ItemType>> GetAllAsync()
            => GetAllAsync(includeAutoGenerated: false, search: null, take: null);

        /// <summary>
        /// The item types ONE company may see: the ones it has registered and
        /// the ones it actually uses.
        ///
        /// <see cref="ItemType"/> is a global catalog with no CompanyId, which
        /// is right for the HS tariff master but wrong for the rows an operator
        /// typed: on an installation serving unrelated tenants, every picker was
        /// listing every other tenant's product names. There is no owner column
        /// to filter on, so membership is DERIVED from the documents and stock
        /// that reference the row -- which also makes it self-healing: the
        /// moment a company puts an item on a document it is theirs, and nothing
        /// can be stranded by a missing registration row.
        ///
        /// Returned as an IQueryable on purpose. Composed into the caller's
        /// query it becomes one `IN (SELECT ...)`, so the paged screen still
        /// filters, counts and orders in SQL -- materialising thousands of ids
        /// and passing them back as parameters would not survive paging.
        /// </summary>
        private IQueryable<int> CompanyItemTypeIds(List<int> companyIds)
        {
            // The company's own registrations -- Mode is irrelevant here; a
            // Default row means "this company has this item on its books",
            // which is exactly the question being asked.
            var registered = _context.CompanyItemTypeSettings
                .Where(s => companyIds.Contains(s.CompanyId)).Select(s => s.ItemTypeId);

            var openings = _context.OpeningStockBalances
                .Where(o => companyIds.Contains(o.CompanyId)).Select(o => o.ItemTypeId);
            var movements = _context.StockMovements
                .Where(m => companyIds.Contains(m.CompanyId)).Select(m => m.ItemTypeId);

            var invoiceLines = _context.InvoiceItems
                .Where(ii => ii.ItemTypeId != null && companyIds.Contains(ii.Invoice!.CompanyId))
                .Select(ii => ii.ItemTypeId!.Value);
            // The filed book of an overlay company can classify a line
            // differently from the bill, so it is a separate source.
            // No Invoice navigation on the adjustment row, so this one
            // joins explicitly rather than walking a property.
            var adjustments =
                from a in _context.InvoiceItemAdjustments
                join i in _context.Invoices on a.InvoiceId equals i.Id
                where a.AdjustedItemTypeId != null && companyIds.Contains(i.CompanyId)
                select a.AdjustedItemTypeId!.Value;

            var purchaseLines = _context.PurchaseItems
                .Where(pi => pi.ItemTypeId != null && companyIds.Contains(pi.PurchaseBill!.CompanyId))
                .Select(pi => pi.ItemTypeId!.Value);
            var debitNoteLines = _context.PurchaseDebitNoteItems
                .Where(d => d.ItemTypeId != null && companyIds.Contains(d.PurchaseDebitNote!.CompanyId))
                .Select(d => d.ItemTypeId!.Value);
            var receiptLines = _context.GoodsReceiptItems
                .Where(g => g.ItemTypeId != null && companyIds.Contains(g.GoodsReceipt!.CompanyId))
                .Select(g => g.ItemTypeId!.Value);
            var challanLines = _context.DeliveryItems
                .Where(d => d.ItemTypeId != null && companyIds.Contains(d.DeliveryChallan!.CompanyId))
                .Select(d => d.ItemTypeId!.Value);
            var orderLines = _context.SalesOrderItems
                .Where(s => s.ItemTypeId != null && companyIds.Contains(s.SalesOrder!.CompanyId))
                .Select(s => s.ItemTypeId!.Value);
            var quoteLines = _context.SalesQuoteItems
                .Where(s => s.ItemTypeId != null && companyIds.Contains(s.SalesQuote!.CompanyId))
                .Select(s => s.ItemTypeId!.Value);

            return registered
                .Union(openings).Union(movements)
                .Union(invoiceLines).Union(adjustments)
                .Union(purchaseLines).Union(debitNoteLines).Union(receiptLines)
                .Union(challanLines).Union(orderLines).Union(quoteLines);
        }

        /// <summary>
        /// Narrow a catalog query to what <paramref name="companyId"/> may see.
        /// An un-adopted HS-import placeholder stays visible to everyone: it is
        /// FBR's published tariff, i.e. installation reference data, and hiding
        /// it would stop a company classifying its first item. IsFavorite is the
        /// adoption signal (see GetAllAsync), so a placeholder someone has taken
        /// over is treated as that company's own row and scoped like one.
        /// </summary>
        private IQueryable<ItemType> ScopeToCompany(
            IQueryable<ItemType> query, IEnumerable<int>? companyIds)
        {
            // NULL and EMPTY mean different things, and the difference is the
            // whole guard. Null is an internal caller (a seeder, an importer,
            // the parameterless overload) asking for the installation. An empty
            // list is a USER who can reach no company -- they get the reference
            // tariff and nothing else, never everything.
            if (companyIds is null) return query;
            var ids = companyIds.Where(i => i > 0).Distinct().ToList();
            var mine = CompanyItemTypeIds(ids);
            return query.Where(it => (it.IsAutoGenerated && !it.IsFavorite) || mine.Contains(it.Id));
        }

        public async Task<List<ItemType>> GetAllAsync(
            bool includeAutoGenerated, string? search, int? take,
            IEnumerable<int>? scopeToCompanyIds = null)
        {
            var query = ScopeToCompany(_context.ItemTypes.Where(it => !it.IsDeleted), scopeToCompanyIds);

            // Placeholders created by the HS import stay out unless asked for —
            // but only while they are STILL placeholders.
            //
            // IsAutoGenerated records that the HS import made the row, and is
            // deliberately never cleared, because the HS association is what it
            // means. Filtering on it alone therefore hid a placeholder FOREVER:
            // an operator could find one, rename it, give it a unit and tick
            // "show in dropdowns", and it still never reached a single document
            // picker. Adoption was a dead end, which is what left an imported
            // catalogue unusable.
            //
            // IsFavorite is the adoption signal — placeholders are created with
            // it false, and ticking it is the operator saying "this one is mine
            // now". So hide the un-adopted ones and let the rest through.
            if (!includeAutoGenerated)
                query = query.Where(it => !it.IsAutoGenerated || it.IsFavorite);

            var term = search?.Trim();
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(it =>
                    EF.Functions.Like(it.Name, "%" + term + "%") ||
                    (it.HSCode != null && EF.Functions.Like(it.HSCode, term + "%")));
            }

            query = query.OrderBy(it => it.Name);
            if (take is > 0) query = query.Take(take.Value);

            return await query.ToListAsync();
        }

        public async Task<(List<ItemType> Rows, int TotalCount)> GetPagedAsync(
            string? search, int page, int pageSize,
            IEnumerable<int>? scopeToCompanyIds = null)
        {
            var query = ScopeToCompany(_context.ItemTypes.Where(it => !it.IsDeleted), scopeToCompanyIds);

            // No IsAutoGenerated filter here, on purpose — see the interface.

            var term = search?.Trim();
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(it =>
                    EF.Functions.Like(it.Name, "%" + term + "%") ||
                    (it.HSCode != null && EF.Functions.Like(it.HSCode, term + "%")));
            }

            var total = await query.CountAsync();

            // Ordering has to happen in SQL, before Skip/Take, or a row can
            // appear on two pages. Both keys are columns, so the on-hand-first
            // sort the pickers use is deliberately NOT applied here: on-hand is
            // computed after the page is fetched and could not order it anyway.
            var rows = await query
                .OrderByDescending(it => it.IsFavorite)
                .ThenBy(it => it.Name)
                .ThenBy(it => it.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            return (rows, total);
        }

        // FindByIdAsync still resolves soft-deleted rows so that propagation
        // / edit-by-id flows see them when needed. The service decides
        // whether to expose the row to the caller.
        public async Task<ItemType?> GetByIdAsync(int id)
            => await _context.ItemTypes.FirstOrDefaultAsync(it => it.Id == id);

        public async Task<ItemType> CreateAsync(ItemType itemType)
        {
            _context.ItemTypes.Add(itemType);
            await _context.SaveChangesAsync();
            return itemType;
        }

        public async Task<ItemType> UpdateAsync(ItemType itemType)
        {
            _context.ItemTypes.Update(itemType);
            await _context.SaveChangesAsync();
            return itemType;
        }

        public async Task DeleteAsync(ItemType itemType)
        {
            // Soft delete only — Restrict FK on InvoiceItems / PurchaseItems /
            // StockMovements would block a hard delete the moment the item
            // has been used anywhere. Service-level guard already enforces
            // "no pending FBR submissions" before we get here.
            itemType.IsDeleted = true;
            _context.ItemTypes.Update(itemType);
            await _context.SaveChangesAsync();
        }

        public async Task<bool> ExistsByNameAndHsCodeAsync(string name, string? hsCode, int? excludeId = null)
        {
            var normalizedHs = string.IsNullOrWhiteSpace(hsCode) ? null : hsCode.Trim();
            var loweredName = (name ?? "").Trim().ToLower();
            return await _context.ItemTypes
                .AnyAsync(it => !it.IsDeleted
                              && it.Name.ToLower() == loweredName
                              && it.HSCode == normalizedHs
                              && (!excludeId.HasValue || it.Id != excludeId.Value));
        }

        public async Task<List<string>> GetSavedHsCodesAsync()
        {
            return await _context.ItemTypes
                .Where(it => !it.IsDeleted && it.HSCode != null && it.HSCode != "")
                .Select(it => it.HSCode!)
                .Distinct()
                .ToListAsync();
        }
    }
}
