using Microsoft.EntityFrameworkCore;
using MyApp.Api.Data;
using MyApp.Api.Models;
using MyApp.Api.Repositories.Interfaces;

namespace MyApp.Api.Repositories.Implementations
{
    public class ItemTypeRepository : IItemTypeRepository
    {
        private readonly AppDbContext _context;

        public ItemTypeRepository(AppDbContext context)
        {
            _context = context;
        }

        public Task<List<ItemType>> GetAllAsync()
            => GetAllAsync(includeAutoGenerated: false, search: null, take: null);

        public async Task<List<ItemType>> GetAllAsync(bool includeAutoGenerated, string? search, int? take)
        {
            var query = _context.ItemTypes.Where(it => !it.IsDeleted);

            // Placeholders created by the HS import stay out unless asked for —
            // but only while they are STILL placeholders.
            //
            // IsAutoGenerated records that the HS import made the row, and is
            // deliberately never cleared, because the HS association is what it
            // means. Filtering on it alone therefore hid a placeholder FOREVER:
            // an operator could find one, rename it, give it a unit and tick
            // "show in dropdowns", and it still never reached a single document
            // picker. Adoption was a dead end, which is what left an imported
            // catalogue unusable.
            //
            // IsFavorite is the adoption signal — placeholders are created with
            // it false, and ticking it is the operator saying "this one is mine
            // now". So hide the un-adopted ones and let the rest through.
            if (!includeAutoGenerated)
                query = query.Where(it => !it.IsAutoGenerated || it.IsFavorite);

            var term = search?.Trim();
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(it =>
                    EF.Functions.Like(it.Name, "%" + term + "%") ||
                    (it.HSCode != null && EF.Functions.Like(it.HSCode, term + "%")));
            }

            query = query.OrderBy(it => it.Name);
            if (take is > 0) query = query.Take(take.Value);

            return await query.ToListAsync();
        }

        public async Task<(List<ItemType> Rows, int TotalCount)> GetPagedAsync(
            string? search, int page, int pageSize)
        {
            var query = _context.ItemTypes.Where(it => !it.IsDeleted);

            // No IsAutoGenerated filter here, on purpose — see the interface.

            var term = search?.Trim();
            if (!string.IsNullOrEmpty(term))
            {
                query = query.Where(it =>
                    EF.Functions.Like(it.Name, "%" + term + "%") ||
                    (it.HSCode != null && EF.Functions.Like(it.HSCode, term + "%")));
            }

            var total = await query.CountAsync();

            // Ordering has to happen in SQL, before Skip/Take, or a row can
            // appear on two pages. Both keys are columns, so the on-hand-first
            // sort the pickers use is deliberately NOT applied here: on-hand is
            // computed after the page is fetched and could not order it anyway.
            var rows = await query
                .OrderByDescending(it => it.IsFavorite)
                .ThenBy(it => it.Name)
                .ThenBy(it => it.Id)
                .Skip((page - 1) * pageSize)
                .Take(pageSize)
                .ToListAsync();

            return (rows, total);
        }

        // FindByIdAsync still resolves soft-deleted rows so that propagation
        // / edit-by-id flows see them when needed. The service decides
        // whether to expose the row to the caller.
        public async Task<ItemType?> GetByIdAsync(int id)
            => await _context.ItemTypes.FirstOrDefaultAsync(it => it.Id == id);

        public async Task<ItemType> CreateAsync(ItemType itemType)
        {
            _context.ItemTypes.Add(itemType);
            await _context.SaveChangesAsync();
            return itemType;
        }

        public async Task<ItemType> UpdateAsync(ItemType itemType)
        {
            _context.ItemTypes.Update(itemType);
            await _context.SaveChangesAsync();
            return itemType;
        }

        public async Task DeleteAsync(ItemType itemType)
        {
            // Soft delete only — Restrict FK on InvoiceItems / PurchaseItems /
            // StockMovements would block a hard delete the moment the item
            // has been used anywhere. Service-level guard already enforces
            // "no pending FBR submissions" before we get here.
            itemType.IsDeleted = true;
            _context.ItemTypes.Update(itemType);
            await _context.SaveChangesAsync();
        }

        public async Task<bool> ExistsByNameAndHsCodeAsync(string name, string? hsCode, int? excludeId = null)
        {
            var normalizedHs = string.IsNullOrWhiteSpace(hsCode) ? null : hsCode.Trim();
            var loweredName = (name ?? "").Trim().ToLower();
            return await _context.ItemTypes
                .AnyAsync(it => !it.IsDeleted
                              && it.Name.ToLower() == loweredName
                              && it.HSCode == normalizedHs
                              && (!excludeId.HasValue || it.Id != excludeId.Value));
        }

        public async Task<List<string>> GetSavedHsCodesAsync()
        {
            return await _context.ItemTypes
                .Where(it => !it.IsDeleted && it.HSCode != null && it.HSCode != "")
                .Select(it => it.HSCode!)
                .Distinct()
                .ToListAsync();
        }
    }
}
