// src/pages/public/LandingPage.jsx
// Hakimi Traders public site — "precision industrial" redesign.
// All motion is hand-rolled (IntersectionObserver reveals, CSS keyframes,
// rAF parallax) — transform/opacity only, so it stays at 60fps on phones.
import { useEffect, useRef, useState } from "react";
import CountUp from "react-countup";
import { useInView } from "react-intersection-observer";
import { Swiper, SwiperSlide } from "swiper/react";
import { Autoplay, Navigation, Pagination } from "swiper/modules";
import "swiper/css";
import "swiper/css/navigation";
import "swiper/css/pagination";
import {
  MdPrecisionManufacturing,
  MdSettingsInputComponent,
  MdTune,
  MdSpeed,
  MdConstruction,
  MdInventory2,
  MdVerified,
  MdBuild,
  MdLocalShipping,
} from "react-icons/md";
import {
  FiMail,
  FiPhone,
  FiMapPin,
  FiSend,
  FiUser,
  FiMessageSquare,
  FiArrowRight,
  FiArrowDownRight,
  FiCheck,
} from "react-icons/fi";
import BrandMark from "../../Components/BrandMark";
/* Build-time snapshot of public/images/products — regenerated by the
   predev/prebuild hooks (scripts/gen-product-manifest.mjs). Used as a
   fallback so the catalogue still renders when the API is unreachable. */
import PRODUCT_MANIFEST from "../../generated/product-manifest.json";
import "./LandingPage.css";

/* ------------------------------------------------------------------ */
/*  Data                                                                */
/* ------------------------------------------------------------------ */

const STATS = [
  { end: 15, suffix: "+", label: "Years in business" },
  { end: 50, suffix: "+", label: "Product lines" },
  { end: 20, suffix: "+", label: "Global brands" },
  { end: 14, suffix: "+", label: "Major clients" },
];

const CATEGORIES = [
  {
    icon: <MdPrecisionManufacturing />,
    title: "Pneumatic Equipment",
    desc: "Push-in fittings, air cylinders, FRL units, solenoid valves and complete pneumatic systems.",
  },
  {
    icon: <MdSettingsInputComponent />,
    title: "Hydraulic Systems",
    desc: "Hydraulic cylinders, hoses, couplings and complete hydraulic circuit components.",
  },
  {
    icon: <MdTune />,
    title: "Industrial Valves",
    desc: "Ball valves, gate valves, butterfly valves and solenoid-operated control valves.",
  },
  {
    icon: <MdSpeed />,
    title: "Pressure & Temperature",
    desc: "Gauges, transmitters, thermometers and industrial instrumentation from top global brands.",
  },
  {
    icon: <MdConstruction />,
    title: "SS / Brass / MS Fittings",
    desc: "Stainless steel, brass and mild steel compression fittings in all sizes and configurations.",
  },
  {
    icon: <MdInventory2 />,
    title: "General Order Supplies",
    desc: "Flexible industrial procurement for diverse maintenance, repair and operations requirements.",
  },
];

/*  Optional metadata for known categories.
    Any folder NOT listed here still appears as a tab —
    its label is auto-generated from the folder name
    (e.g. "my-new-category" → "My New Category").               */
const CATEGORY_META = {
  pneumatic:              { label: "Pneumatic Accessories", products: ["Push-in Fittings (Straight / Elbow / Tee)","Pneumatic Tubing (PA / PU / Nylon)","Quick Connectors & Couplings","Flow Control Valves","Check Valves","Mufflers & Silencers","Pneumatic Manifolds"] },
  frl:                    { label: "Air Service / FRL",     products: ["Filter-Regulator-Lubricator (FRL) Units","Air Filters (Particulate & Coalescing)","Precision Regulators","Line Lubricators","Air Dryers","Service Units (Modular)"] },
  cylinders:              { label: "Cylinders",             products: ["Double Acting Cylinders (Standard / Compact)","Single Acting Cylinders","Round Body (Tie-rod) Cylinders","Profile Cylinders","Rodless Cylinders","Cylinder Repair Kits"] },
  valves:                 { label: "Valves",                products: ["5/2 & 5/3 Solenoid Valves","3/2 Way Valves","Directional Control Valves","Valve Manifolds","Pneumatic & Hydraulic Ball Valves","Proportional Valves"] },
  hydraulics:             { label: "Hydraulics",            products: ["Hydraulic Cylinders","Hydraulic Hoses & Fittings","Hydraulic Pumps","Control Valves","Pressure Gauges for Hydraulics","Hydraulic Seals & Repair Kits"] },
  "industrial-valves":    { label: "Industrial Valves",     products: ["SS Ball Valves (Manual & Actuated)","Gate Valves","Globe Valves","Butterfly Valves","Needle Valves","Safety Relief Valves"] },
  "pressure-instruments": { label: "Pressure Instruments",  products: ["Bourdon Tube Pressure Gauges","Differential Pressure Gauges","Pressure Transmitters","Pressure Switches","Diaphragm Seals","Manometers"] },
  "temperature-instruments": { label: "Temperature Instruments", products: ["Bi-metal Thermometers","Temperature Transmitters","Thermocouples (Type J/K/T)","RTD Sensors (PT100)","Temperature Switches","Digital Indicators"] },
  "ss-fittings":          { label: "SS Fittings",           products: ["SS Compression Fittings (Swagelok-type)","SS Tube Fittings (Straight / Elbow / Tee / Cross)","SS NPT Adapters","SS Unions & Couplings","SS Ferrule Sets","High-Pressure Fittings"] },
  "brass-fittings":       { label: "Brass Fittings",        products: ["Brass Compression Fittings","Brass Push-in Fittings","Brass NPT / BSP Fittings","Brass Barb Fittings","Brass Plug / Cap / Bush","Brass Unions & Nipples"] },
  "ms-fittings":          { label: "MS Fittings",           products: ["MS Compression Fittings","MS Pipe Fittings (Tee / Elbow / Reducer)","MS Flanges","MS Unions","MS Hex Nipples","MS Tube Connectors"] },
  "repair-kits":          { label: "Repair Kits",           products: ["Pneumatic Cylinder Repair Kits","FRL Unit Service Kits","Solenoid Valve Coils & Seals","O-Ring Assortments","Seal Kits (NBR / Viton / PTFE)","Diaphragm & Membrane Kits"] },
};

/** Convert folder name to display label: "my-new-category" → "My New Category" */
function folderToLabel(folder) {
  return folder
    .split("-")
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(" ");
}

const BRANDS = [
  "Legris", "SMC", "Norgren", "WIKA", "Swagelok", "FESTO",
  "CKD", "Sang-A", "Parker", "Nuova Fima", "Burkert", "AirTac",
  "ASCO", "MAC", "WABCO", "Southman", "Whitey", "NAB",
  "SNS", "Nitta Moore", "Danfoss", "JUMO", "Wade",
  "Imperial England", "EAO", "KTZ",
];

const CLIENTS = [
  { name: "Mekotex", industry: "Textile" },
  { name: "Tata Pakistan", industry: "Industrial" },
  { name: "Artistic Denim", industry: "Textile" },
  { name: "Medicam Group", industry: "Pharma" },
  { name: "Sapphire", industry: "Textile" },
  { name: "Siddiqsons", industry: "Textile" },
  { name: "Lotte Kolson", industry: "Food" },
  { name: "Continental Biscuits", industry: "Food" },
  { name: "Soorty", industry: "Textile" },
  { name: "Mundia Export", industry: "Textile" },
  { name: "Artistic Garment", industry: "Textile" },
  { name: "Crescent Bahuman", industry: "Textile" },
  { name: "Lucky Textile", industry: "Textile" },
  { name: "Gul Ahmed", industry: "Textile" },
];

const INDUSTRY_COLORS = {
  Textile:    { bg: "#dbeafe", color: "#1d4ed8" },
  Industrial: { bg: "#fce7f3", color: "#be185d" },
  Pharma:     { bg: "#dcfce7", color: "#15803d" },
  Food:       { bg: "#fef3c7", color: "#b45309" },
};

const WHY_CARDS = [
  {
    icon: <MdVerified />,
    title: "Quality Products",
    desc: "We source exclusively from premium global brands, ensuring genuine parts with full traceability and manufacturer warranties.",
  },
  {
    icon: <MdBuild />,
    title: "Expert Repair & Servicing",
    desc: "Skilled in-house servicing of pneumatic cylinders, FRL units, solenoid valves and complete pneumatic assemblies.",
  },
  {
    icon: <MdLocalShipping />,
    title: "Reliable Supply Chain",
    desc: "Timely delivery across Karachi and Pakistan, competitive pricing, and a well-stocked inventory for fast dispatch.",
  },
];

const ROTATING_WORDS = [
  "Pneumatics",
  "Hydraulics",
  "Instrumentation",
  "Industrial Fittings",
  "General Order Supplies",
];

const TICKER = [
  "Push-in Fittings", "FRL Units", "Solenoid Valves", "Air Cylinders",
  "Pressure Gauges", "Hydraulic Hoses", "SS Compression Fittings",
  "Ball Valves", "Thermocouples", "Quick Couplings",
  "Temperature Transmitters", "Repair Kits",
];

/* ------------------------------------------------------------------ */
/*  Small presentational pieces                                         */
/* ------------------------------------------------------------------ */

/** Headline word split into letters that rise out of a clipping mask. */
function SplitWord({ word, baseDelay = 0, className = "" }) {
  return (
    <span className={`lp-split ${className}`} aria-hidden="true">
      {word.split("").map((ch, i) => (
        <span key={i} className="lp-split__mask">
          <span
            className="lp-split__char"
            style={{ animationDelay: `${baseDelay + i * 55}ms` }}
          >
            {ch}
          </span>
        </span>
      ))}
    </span>
  );
}

/** Cycling specialty word. A hidden ghost of the longest word reserves
    width so the line never reflows as words swap. */
function RotatingWord() {
  const [idx, setIdx] = useState(0);
  useEffect(() => {
    const t = setInterval(
      () => setIdx((i) => (i + 1) % ROTATING_WORDS.length),
      2600
    );
    return () => clearInterval(t);
  }, []);
  return (
    <span className="lp-rotate">
      <span className="lp-rotate__ghost" aria-hidden="true">
        General Order Supplies
      </span>
      <span key={idx} className="lp-rotate__word">
        {ROTATING_WORDS[idx]}
      </span>
    </span>
  );
}

/** Numbered editorial section header. */
function SectionHead({ index, eyebrow, title, sub, light = false }) {
  return (
    <div className={`lp-head${light ? " lp-head--light" : ""}`} data-reveal>
      <p className="lp-head__eyebrow">
        <span className="lp-head__index">{index}</span>
        <span className="lp-head__rule" aria-hidden="true" />
        {eyebrow}
      </p>
      <h2 className="lp-head__title">{title}</h2>
      {sub && <p className="lp-head__sub">{sub}</p>}
    </div>
  );
}

/** Animated stat counter (starts when scrolled into view). */
function StatCounter({ end, suffix, label }) {
  const { ref, inView } = useInView({ triggerOnce: true, threshold: 0.3 });
  return (
    <div className="lp-stat" ref={ref}>
      <span className="lp-stat__number">
        {inView ? <CountUp end={end} duration={2.2} /> : "0"}
        <span className="lp-stat__suffix">{suffix}</span>
      </span>
      <span className="lp-stat__label">{label}</span>
    </div>
  );
}

/* ------------------------------------------------------------------ */
/*  LandingPage                                                         */
/* ------------------------------------------------------------------ */
export default function LandingPage() {
  const [activeTab, setActiveTab] = useState(0);
  const [productTabs, setProductTabs] = useState([]); // dynamic categories from API
  const [categoryImages, setCategoryImages] = useState({}); // { folder: [url, ...] }
  const [formData, setFormData] = useState({ name: "", email: "", phone: "", message: "" });
  const [formStatus, setFormStatus] = useState(null); // 'sending' | 'sent' | 'error'
  const heroRef = useRef(null);

  const apiBase = window._env_?.API_URL || "/api";

  /* Scroll-reveal: one observer over every [data-reveal] element.
     Re-runs when product tabs arrive so late-mounted nodes get observed. */
  useEffect(() => {
    const els = document.querySelectorAll("[data-reveal]:not(.is-in)");
    if (!("IntersectionObserver" in window)) {
      els.forEach((el) => el.classList.add("is-in"));
      return;
    }
    const io = new IntersectionObserver(
      (entries) => {
        entries.forEach((en) => {
          if (en.isIntersecting) {
            en.target.classList.add("is-in");
            io.unobserve(en.target);
          }
        });
      },
      { threshold: 0.12, rootMargin: "0px 0px -8% 0px" }
    );
    els.forEach((el) => io.observe(el));
    return () => io.disconnect();
  }, [productTabs.length]);

  /* Deep links: /#products etc. — the SPA mounts after navigation, so the
     browser's native fragment scroll misses. Re-anchor once after mount. */
  useEffect(() => {
    const id = window.location.hash?.slice(1);
    if (!id) return;
    const raf = requestAnimationFrame(() => {
      document.getElementById(id)?.scrollIntoView({ behavior: "auto", block: "start" });
    });
    return () => cancelAnimationFrame(raf);
  }, []);

  /* Hero mouse parallax (fine pointers only, rAF-throttled). */
  useEffect(() => {
    if (!window.matchMedia("(pointer: fine)").matches) return;
    const hero = heroRef.current;
    if (!hero) return;
    let raf = 0;
    const onMove = (e) => {
      if (raf) return;
      raf = requestAnimationFrame(() => {
        raf = 0;
        const r = hero.getBoundingClientRect();
        hero.style.setProperty("--px", (((e.clientX - r.left) / r.width) - 0.5).toFixed(3));
        hero.style.setProperty("--py", (((e.clientY - r.top) / r.height) - 0.5).toFixed(3));
      });
    };
    hero.addEventListener("pointermove", onMove);
    return () => {
      hero.removeEventListener("pointermove", onMove);
      cancelAnimationFrame(raf);
    };
  }, []);

  /* Fetch category list from API on mount, then preload all category images.
     The API is the source of truth (operators can add images on the server
     without a rebuild); the build-time manifest is the fallback so the
     catalogue still renders when the API is down or slow (>6s). */
  useEffect(() => {
    let disposed = false;
    const ctrl = new AbortController();
    const timeout = setTimeout(() => ctrl.abort(), 6000);

    const toTabs = (categories) =>
      categories.map((cat) => {
        const meta = CATEGORY_META[cat.name];
        return {
          id: cat.name,
          label: meta?.label || folderToLabel(cat.name),
          folder: cat.name,
          products: meta?.products || [],
          imageCount: cat.imageCount,
        };
      });

    const applyManifest = () => {
      if (disposed) return;
      const names = Object.keys(PRODUCT_MANIFEST).sort();
      if (names.length === 0) return; // nothing to fall back to — keep skeleton
      setProductTabs(toTabs(names.map((name) => ({ name, imageCount: PRODUCT_MANIFEST[name].length }))));
      setCategoryImages({ ...PRODUCT_MANIFEST });
    };

    fetch(`${apiBase}/product-images`, { signal: ctrl.signal })
      .then((res) => (res.ok ? res.json() : []))
      .then((categories) => {
        clearTimeout(timeout);
        if (disposed) return;
        if (!Array.isArray(categories) || categories.length === 0) {
          applyManifest();
          return;
        }
        setProductTabs(toTabs(categories));
        // Preload images for all categories in the background
        categories.forEach((cat) => {
          fetch(`${apiBase}/product-images/${cat.name}`)
            .then((res) => (res.ok ? res.json() : []))
            .then((images) => {
              if (disposed) return;
              const fallback = PRODUCT_MANIFEST[cat.name] || [];
              setCategoryImages((prev) => ({
                ...prev,
                [cat.name]: images.length > 0 ? images : fallback,
              }));
            })
            .catch(() => {
              if (disposed || !PRODUCT_MANIFEST[cat.name]) return;
              setCategoryImages((prev) => ({ ...prev, [cat.name]: PRODUCT_MANIFEST[cat.name] }));
            });
        });
      })
      .catch(() => {
        clearTimeout(timeout);
        applyManifest();
      });

    return () => {
      disposed = true;
      clearTimeout(timeout);
      ctrl.abort();
    };
  }, [apiBase]);

  /* Spotlight hover — writes cursor coords into CSS vars on the card. */
  const onSpotMove = (e) => {
    const card = e.target.closest(".lp-spot");
    if (!card) return;
    const r = card.getBoundingClientRect();
    card.style.setProperty("--mx", `${e.clientX - r.left}px`);
    card.style.setProperty("--my", `${e.clientY - r.top}px`);
  };

  const goTo = (sel) => (e) => {
    e.preventDefault();
    document.querySelector(sel)?.scrollIntoView({ behavior: "smooth", block: "start" });
  };

  const handleFormChange = (e) => {
    setFormData((prev) => ({ ...prev, [e.target.name]: e.target.value }));
  };

  const handleFormSubmit = (e) => {
    e.preventDefault();
    setFormStatus("sending");
    // Simulate sending (replace with actual API call)
    setTimeout(() => setFormStatus("sent"), 1500);
  };

  const activeProduct = productTabs[activeTab] || { id: "", label: "", folder: "", products: [] };
  const activeImages = categoryImages[activeProduct.folder] || [];

  /* Duplicate rows for seamless marquee loops */
  const brandsRow1 = [...BRANDS.slice(0, 13), ...BRANDS.slice(0, 13)];
  const brandsRow2 = [...BRANDS.slice(13), ...BRANDS.slice(13)];
  const tickerRow = [...TICKER, ...TICKER];

  return (
    <div className="lp-page">
      {/* ============================================================ */}
      {/*  HERO                                                        */}
      {/* ============================================================ */}
      <section id="home" className="lp-hero" ref={heroRef}>
        <div className="lp-hero__bg" aria-hidden="true">
          <span className="lp-orb lp-orb--a" />
          <span className="lp-orb lp-orb--b" />
          <span className="lp-orb lp-orb--c" />
          <span className="lp-hero__grid" />
          <span className="lp-hero__noise" />
        </div>

        <div className="lp-hero__inner">
          <p className="lp-hero__eyebrow lp-rise" style={{ "--rise-d": "120ms" }}>
            <BrandMark size={18} />
            Karachi, Pakistan&ensp;&mdash;&ensp;Est. 2009
          </p>

          <h1 className="lp-hero__title">
            <span className="lp-sr">Hakimi Traders</span>
            <SplitWord word="HAKIMI" baseDelay={250} className="lp-split--solid" />
            <SplitWord word="TRADERS" baseDelay={640} className="lp-split--stroke" />
          </h1>

          <div className="lp-hero__rotline lp-rise" style={{ "--rise-d": "1150ms" }}>
            <span className="lp-hero__slash" aria-hidden="true">/</span>
            <RotatingWord />
            <span className="lp-hero__slash" aria-hidden="true">/</span>
          </div>

          <p className="lp-hero__desc lp-rise" style={{ "--rise-d": "1300ms" }}>
            Genuine pneumatic, hydraulic and instrumentation components from
            20+ global brands &mdash; stocked in Karachi, serviced in-house,
            and supplied to Pakistan&apos;s leading manufacturers since 2009.
          </p>

          <div className="lp-hero__ctas lp-rise" style={{ "--rise-d": "1450ms" }}>
            <a href="#products" className="lp-btn lp-btn--primary" onClick={goTo("#products")}>
              Browse the catalogue <FiArrowRight aria-hidden="true" />
            </a>
            <a href="#contact" className="lp-btn lp-btn--ghost" onClick={goTo("#contact")}>
              Talk to us
            </a>
          </div>
        </div>

        <div className="lp-hero__cue lp-rise" style={{ "--rise-d": "1700ms" }} aria-hidden="true">
          <span className="lp-hero__cue-line" />
        </div>

        {/* Conveyor-belt ticker of what we stock */}
        <div className="lp-ticker" aria-hidden="true">
          <div className="lp-ticker__track">
            {tickerRow.map((t, i) => (
              <span key={i} className="lp-ticker__item">
                <span className="lp-ticker__diamond" />
                {t}
              </span>
            ))}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  01 — ABOUT                                                  */}
      {/* ============================================================ */}
      <section id="about" className="lp-sec lp-sec--light lp-about">
        <div className="lp-container">
          <div className="lp-about__grid">
            <div className="lp-about__text">
              <SectionHead
                index="01"
                eyebrow="Who we are"
                title={<>Industrial supply, <em>done properly.</em></>}
              />
              <div data-reveal style={{ "--rd": "120ms" }}>
                <p>
                  Hakimi Traders is a Karachi-based specialist supplier of pneumatic, hydraulic
                  and industrial equipment, serving Pakistan&apos;s leading manufacturers since 2009.
                  We supply genuine components from over 20 internationally recognized brands —
                  giving our clients reliable, efficient and cost-effective industrial solutions.
                </p>
                <p>
                  From push-in fittings and FRL units to solenoid valves, pressure instruments
                  and complete cylinder assemblies — our inventory and expert team ensure you get
                  exactly what your plant needs, when you need it.
                </p>
                <div className="lp-about__badges">
                  <span className="lp-badge">NTN&nbsp;4228937-8</span>
                  <span className="lp-badge">STRN&nbsp;3277876175852</span>
                  <span className="lp-badge lp-badge--accent">ISO-grade sourcing</span>
                </div>
              </div>
            </div>

            {/* Composed visual: orbit ring + floating capability chips */}
            <div className="lp-about__visual" data-reveal style={{ "--rd": "180ms" }} aria-hidden="true">
              <span className="lp-about__orbit" />
              <span className="lp-about__orbit lp-about__orbit--inner" />
              <div className="lp-about__core">
                <BrandMark size={84} />
                <span className="lp-about__core-name">HAKIMI TRADERS</span>
                <span className="lp-about__core-since">EST. 2009 — KARACHI</span>
              </div>
              <div className="lp-about__chip lp-about__chip--1">
                <MdVerified />
                <div>
                  <strong>Genuine parts</strong>
                  <span>20+ global brands</span>
                </div>
              </div>
              <div className="lp-about__chip lp-about__chip--2">
                <MdBuild />
                <div>
                  <strong>In-house servicing</strong>
                  <span>Cylinders · FRL · valves</span>
                </div>
              </div>
              <div className="lp-about__chip lp-about__chip--3">
                <MdLocalShipping />
                <div>
                  <strong>Nationwide supply</strong>
                  <span>Karachi → all Pakistan</span>
                </div>
              </div>
            </div>
          </div>

          {/* Stats band */}
          <div className="lp-stats" data-reveal>
            {STATS.map((s) => (
              <StatCounter key={s.label} {...s} />
            ))}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  02 — PRODUCT CATEGORIES                                     */}
      {/* ============================================================ */}
      <section id="categories" className="lp-sec lp-sec--light lp-categories">
        <div className="lp-container">
          <SectionHead
            index="02"
            eyebrow="What we supply"
            title={<>Six verticals. <em>One supplier.</em></>}
            sub="Comprehensive industrial supply across our core product families — click any card to jump into the catalogue."
          />

          <div className="lp-categories__grid" onPointerMove={onSpotMove}>
            {CATEGORIES.map((cat, i) => (
              <article
                key={cat.title}
                className="lp-cat-card lp-spot"
                data-reveal
                style={{ "--rd": `${i * 70}ms` }}
                onClick={() => document.querySelector("#products")?.scrollIntoView({ behavior: "smooth" })}
                role="button"
                tabIndex={0}
                onKeyDown={(e) => e.key === "Enter" && document.querySelector("#products")?.scrollIntoView({ behavior: "smooth" })}
                aria-label={`${cat.title} — view products`}
              >
                <span className="lp-cat-card__num" aria-hidden="true">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <div className="lp-cat-card__icon" aria-hidden="true">{cat.icon}</div>
                <h3 className="lp-cat-card__title">{cat.title}</h3>
                <p className="lp-cat-card__desc">{cat.desc}</p>
                <span className="lp-cat-card__cta">
                  View products <FiArrowRight aria-hidden="true" />
                </span>
              </article>
            ))}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  03 — PRODUCTS SHOWCASE                                      */}
      {/* ============================================================ */}
      <section id="products" className="lp-sec lp-sec--dark lp-products">
        <div className="lp-container">
          <SectionHead
            light
            index="03"
            eyebrow="Our range"
            title={<>The <em>catalogue.</em></>}
            sub="Browse pneumatic, hydraulic and instrumentation components by family."
          />

          {productTabs.length > 0 ? (
            <>
              <div className="lp-products__tabs-wrap" data-reveal>
                <div className="lp-products__tabs" role="tablist" aria-label="Product categories">
                  {productTabs.map((tab, i) => (
                    <button
                      key={tab.id}
                      type="button"
                      className={`lp-products__tab${activeTab === i ? " lp-products__tab--active" : ""}`}
                      onClick={() => setActiveTab(i)}
                      role="tab"
                      aria-selected={activeTab === i}
                      aria-controls={`tabpanel-${tab.id}`}
                      id={`tab-${tab.id}`}
                    >
                      {tab.label}
                    </button>
                  ))}
                </div>
              </div>

              <div
                key={activeProduct.id}
                className="lp-products__panel"
                role="tabpanel"
                id={`tabpanel-${activeProduct.id}`}
                aria-labelledby={`tab-${activeProduct.id}`}
              >
                <div className="lp-products__panel-inner">
                  {/* Carousel */}
                  <div className="lp-products__carousel">
                    {activeImages.length > 0 ? (
                      <Swiper
                        key={activeProduct.folder}
                        modules={[Autoplay, Navigation, Pagination]}
                        spaceBetween={0}
                        slidesPerView={1}
                        navigation
                        pagination={{ clickable: true }}
                        autoplay={{ delay: 2400, disableOnInteraction: false }}
                        loop={activeImages.length > 1}
                        observer={true}
                        observeParents={true}
                        className="lp-swiper"
                      >
                        {activeImages.map((src, idx) => (
                          <SwiperSlide key={src}>
                            <div className="lp-swiper__slide">
                              <img
                                src={src}
                                alt={`${activeProduct.label} product image ${idx + 1}`}
                                loading={idx === 0 ? "eager" : "lazy"}
                                onError={(e) => {
                                  e.currentTarget.style.display = "none";
                                }}
                              />
                            </div>
                          </SwiperSlide>
                        ))}
                      </Swiper>
                    ) : (
                      <div className="lp-swiper__slide lp-swiper__slide--loading">
                        <span className="lp-skel lp-skel--media" />
                        <span className="lp-loading-label">Loading catalogue…</span>
                      </div>
                    )}
                  </div>

                  {/* Product list */}
                  <div className="lp-products__list">
                    <h3 className="lp-products__list-title">{activeProduct.label}</h3>
                    <ul className="lp-products__items" role="list">
                      {activeProduct.products.map((p, i) => (
                        <li key={p} className="lp-products__item">
                          <span className="lp-products__item-num" aria-hidden="true">
                            {String(i + 1).padStart(2, "0")}
                          </span>
                          {p}
                        </li>
                      ))}
                    </ul>
                    <a
                      href="#contact"
                      className="lp-btn lp-btn--primary lp-btn--sm"
                      onClick={goTo("#contact")}
                    >
                      Enquire about this category <FiArrowRight aria-hidden="true" />
                    </a>
                  </div>
                </div>
              </div>
            </>
          ) : (
            /* Skeleton while the catalogue API loads */
            <div className="lp-products__skeleton" aria-hidden="true">
              <div className="lp-products__skel-tabs">
                {Array.from({ length: 6 }).map((_, i) => (
                  <span key={i} className="lp-skel lp-skel--pill" />
                ))}
              </div>
              <div className="lp-products__skel-panel">
                <span className="lp-skel lp-skel--media" />
                <div className="lp-products__skel-lines">
                  {Array.from({ length: 6 }).map((_, i) => (
                    <span key={i} className="lp-skel lp-skel--line" />
                  ))}
                </div>
              </div>
            </div>
          )}
        </div>
      </section>

      {/* ============================================================ */}
      {/*  04 — TRUSTED BRANDS                                         */}
      {/* ============================================================ */}
      <section id="brands" className="lp-sec lp-sec--dark lp-brands">
        <div className="lp-container">
          <SectionHead
            light
            index="04"
            eyebrow="Our partners"
            title={<>Authorized stockists of <em>the world&apos;s best.</em></>}
            sub="Genuine components from over 20 leading international manufacturers."
          />
        </div>

        <div className="lp-brands__rows" data-reveal>
          <div className="lp-brands__track-wrap" aria-label="Brand logos row 1">
            <div className="lp-brands__track lp-brands__track--left">
              {brandsRow1.map((b, i) => (
                <div key={`${b}-${i}`} className="lp-brand-badge">
                  <span className="lp-brand-badge__mono" aria-hidden="true">{b[0]}</span>
                  {b}
                </div>
              ))}
            </div>
          </div>

          <div className="lp-brands__track-wrap" aria-label="Brand logos row 2">
            <div className="lp-brands__track lp-brands__track--right">
              {brandsRow2.map((b, i) => (
                <div key={`${b}-${i}`} className="lp-brand-badge">
                  <span className="lp-brand-badge__mono" aria-hidden="true">{b[0]}</span>
                  {b}
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  05 — CLIENTS                                                */}
      {/* ============================================================ */}
      <section id="clients" className="lp-sec lp-sec--light lp-clients">
        <div className="lp-container">
          <SectionHead
            index="05"
            eyebrow="Who trusts us"
            title={<>Trusted by Pakistan&apos;s <em>manufacturers.</em></>}
            sub="Textile mills, pharma plants, food producers and heavy industry — running on parts we supply."
          />

          <div className="lp-clients__grid">
            {CLIENTS.map((c, i) => {
              const style = INDUSTRY_COLORS[c.industry] ?? { bg: "#ede9fe", color: "#5b21b6" };
              return (
                <div
                  key={c.name}
                  className="lp-client-card"
                  data-reveal
                  style={{ "--rd": `${(i % 7) * 60}ms`, "--ind": style.color }}
                >
                  <div className="lp-client-card__initials" aria-hidden="true">
                    {c.name.split(" ").map((w) => w[0]).slice(0, 2).join("")}
                  </div>
                  <span className="lp-client-card__name">{c.name}</span>
                  <span
                    className="lp-client-card__industry"
                    style={{ background: style.bg, color: style.color }}
                  >
                    {c.industry}
                  </span>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  06 — WHY CHOOSE US + CTA                                    */}
      {/* ============================================================ */}
      <section id="why" className="lp-sec lp-sec--dark lp-why">
        <div className="lp-container">
          <SectionHead
            light
            index="06"
            eyebrow="Our advantage"
            title={<>Why plants <em>choose Hakimi.</em></>}
          />

          <div className="lp-why__grid">
            {WHY_CARDS.map((card, i) => (
              <div
                key={card.title}
                className="lp-why-card"
                data-reveal
                style={{ "--rd": `${i * 120}ms` }}
              >
                <span className="lp-why-card__num" aria-hidden="true">
                  {String(i + 1).padStart(2, "0")}
                </span>
                <div className="lp-why-card__icon" aria-hidden="true">{card.icon}</div>
                <h3 className="lp-why-card__title">{card.title}</h3>
                <p className="lp-why-card__desc">{card.desc}</p>
              </div>
            ))}
          </div>

          {/* Inline CTA panel */}
          <div className="lp-cta" data-reveal>
            <span className="lp-cta__glow" aria-hidden="true" />
            <div className="lp-cta__text">
              <h3>
                Need a specific part? <em>We probably stock it.</em>
              </h3>
              <p>
                Call with a part number or a photo — our team will identify it,
                quote it and arrange supply.
              </p>
            </div>
            <div className="lp-cta__actions">
              <a href="tel:+923355285380" className="lp-btn lp-btn--primary">
                <FiPhone aria-hidden="true" /> 0335-5285380
              </a>
              <a href="#contact" className="lp-btn lp-btn--ghost" onClick={goTo("#contact")}>
                Send an enquiry <FiArrowDownRight aria-hidden="true" />
              </a>
            </div>
          </div>
        </div>
      </section>

      {/* ============================================================ */}
      {/*  07 — CONTACT                                                */}
      {/* ============================================================ */}
      <section id="contact" className="lp-sec lp-sec--light lp-contact">
        <div className="lp-container">
          <SectionHead
            index="07"
            eyebrow="Get in touch"
            title={<>Let&apos;s source <em>your next part.</em></>}
            sub="Send us an enquiry or visit our office in Karachi — we respond fast."
          />

          <div className="lp-contact__grid">
            {/* Form */}
            <div className="lp-contact__form-wrap" data-reveal>
              <form
                className="lp-contact__form"
                onSubmit={handleFormSubmit}
                noValidate
                aria-label="Contact form"
              >
                <div className="lp-form-row">
                  <div className="lp-form-group">
                    <label htmlFor="cf-name">
                      <FiUser aria-hidden="true" /> Full name
                    </label>
                    <input
                      id="cf-name"
                      type="text"
                      name="name"
                      placeholder="Your full name"
                      value={formData.name}
                      onChange={handleFormChange}
                      required
                      autoComplete="name"
                    />
                  </div>
                  <div className="lp-form-group">
                    <label htmlFor="cf-phone">
                      <FiPhone aria-hidden="true" /> Phone
                    </label>
                    <input
                      id="cf-phone"
                      type="tel"
                      name="phone"
                      placeholder="03XX-XXXXXXX"
                      value={formData.phone}
                      onChange={handleFormChange}
                      autoComplete="tel"
                    />
                  </div>
                </div>
                <div className="lp-form-group">
                  <label htmlFor="cf-email">
                    <FiMail aria-hidden="true" /> Email address
                  </label>
                  <input
                    id="cf-email"
                    type="email"
                    name="email"
                    placeholder="your@email.com"
                    value={formData.email}
                    onChange={handleFormChange}
                    required
                    autoComplete="email"
                  />
                </div>
                <div className="lp-form-group">
                  <label htmlFor="cf-message">
                    <FiMessageSquare aria-hidden="true" /> Message
                  </label>
                  <textarea
                    id="cf-message"
                    name="message"
                    rows={5}
                    placeholder="Tell us about your requirements — part numbers, brands, quantities…"
                    value={formData.message}
                    onChange={handleFormChange}
                    required
                  />
                </div>

                <button
                  type="submit"
                  className="lp-btn lp-btn--primary lp-btn--send"
                  disabled={formStatus === "sending" || formStatus === "sent"}
                >
                  {formStatus === "sending" ? (
                    <>
                      <span className="lp-spinner" aria-hidden="true" /> Sending…
                    </>
                  ) : formStatus === "sent" ? (
                    <>
                      <FiCheck aria-hidden="true" /> Message sent
                    </>
                  ) : (
                    <>
                      <FiSend aria-hidden="true" /> Send enquiry
                    </>
                  )}
                </button>

                {formStatus === "sent" && (
                  <p className="lp-form-success" role="status">
                    <FiCheck aria-hidden="true" /> Thank you! We&apos;ll be in touch shortly.
                  </p>
                )}
              </form>
            </div>

            {/* Info + map */}
            <div className="lp-contact__info" data-reveal style={{ "--rd": "140ms" }}>
              <div className="lp-contact__cards">
                <div className="lp-info-card">
                  <span className="lp-info-card__icon"><FiMail aria-hidden="true" /></span>
                  <div>
                    <strong>Email</strong>
                    <a href="mailto:hakimitraders111@gmail.com">hakimitraders111@gmail.com</a>
                  </div>
                </div>

                <div className="lp-info-card">
                  <span className="lp-info-card__icon"><FiPhone aria-hidden="true" /></span>
                  <div>
                    <strong>Director — Sakina Dossaji</strong>
                    <a href="tel:+923355285380">0335-5285380</a>
                  </div>
                </div>

                <div className="lp-info-card">
                  <span className="lp-info-card__icon"><FiPhone aria-hidden="true" /></span>
                  <div>
                    <strong>Technical — Murtaza</strong>
                    <a href="tel:+923313368883">0331-3368883</a>
                  </div>
                </div>

                <div className="lp-info-card">
                  <span className="lp-info-card__icon"><FiMapPin aria-hidden="true" /></span>
                  <div>
                    <strong>Office address</strong>
                    <address>
                      Shop# 21, Falak Corporate City,<br />
                      Talpur Road, opposite City Post Office,<br />
                      Karachi, Pakistan
                    </address>
                  </div>
                </div>
              </div>

              <div className="lp-contact__map">
                <iframe
                  title="Hakimi Traders location — Falak Corporate City, Talpur Road, Karachi"
                  src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3619.8!2d67.0099!3d24.8607!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3eb33e2c0000003%3A0x0!2sTalpur%20Rd%2C%20Karachi!5e0!3m2!1sen!2s!4v1"
                  width="100%"
                  height="240"
                  style={{ border: 0 }}
                  allowFullScreen
                  loading="lazy"
                  referrerPolicy="no-referrer-when-downgrade"
                />
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
}
